# Generated by Django 3.1.4 on 2021-02-05 06:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210205_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(default='abcd'),
            preserve_default=False,
        ),
    ]
