# Generated by Django 3.1.7 on 2021-04-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_act', '0003_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
