# Generated by Django 3.1.7 on 2021-04-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_act', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
