# Generated by Django 3.1.7 on 2021-04-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_act', '0004_auto_20210408_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
