# Generated by Django 3.1.7 on 2021-04-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_act', '0006_auto_20210409_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
